### ISSUE TITLE
Spigot 1.13.2

### ISSUE THREAD

**Issue by Rocologo** [parallelblock/NuVotifier#109]
Hi I just upgraded to Spigot 1.13.2

And I get this error everytime I start my server. It looks NuVitifier, but I guess it could be VotingPlugin 5.16 too? 

```
[19:17:25] [Votifier NIO worker/ERROR]: [Votifier] Unable to process vote from /104.192.2.186:45964
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_161]
	at com.vexsoftware.votifier.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[nuvotifier-2.4.1.jar:?]
	at com.vexsoftware.votifier.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106) ~[nuvotifier-2.4.1.jar:?]
	at com.vexsoftware.votifier.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:343) ~[nuvotifier-2.4.1.jar:?]
	at com.vexsoftware.votifier.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [nuvotifier-2.4.1.jar:?]
	at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [nuvotifier-2.4.1.jar:?]
	at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) [nuvotifier-2.4.1.jar:?]
	at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) [nuvotifier-2.4.1.jar:?]
	at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [nuvotifier-2.4.1.jar:?]
	at com.vexsoftware.votifier.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [nuvotifier-2.4.1.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

**Comment by Ichbinjoe** [comment]
http://104.192.2.186/

Got this crazy feeling this isn't a legit vote. Expected behavior.

**Comment by Rocologo** [comment]
??? How can a vote not be legit???

Are you saying that I must report the bug to VotingPlugin?

**Comment by Rocologo** [comment]
The is thrown every time i start my server and then again and again...

**Comment by DutchUser** [comment]
Click on the IP. It says "kobi's scanbox"

**Comment by Rocologo** [comment]
I guess its a router/firewall/nas or something...  my guess is that the minecraft player is behind this router/firewall

How do i get rid of this bug?

**Comment by Ichbinjoe** [comment]
This is not a bug. There is no anomalous behavior here. Nothing to get rid of. NuVotifier is accurately alerting you that a connection it got was reset by the peer (kobi's scanbox). There is no wrong behavior here.

**Comment by Rocologo** [comment]
But there is no players online and i get the ‘message’ again and again. If it is not nuvoting, the it must be VotingPlugin

**Comment by Ichbinjoe** [comment]
No lol. I promise you, there is nothing wrong here. Nothing is working incorrectly. NuVotifier works independently of players being on the server. Thats not how voting works. Its not really worthwhile to explain, but just understand that this error is expected, and is not wrong in any way.

**Comment by xD** [comment]
sorry bout dat. the errors should stop as I've stopped port scanning <3

**Comment by Rocologo** [comment]
Portscanning, that explains the strange behavior, but not why you portscanned my server... 

I guess i can enable nuvotifier an votingplugin again then

**Comment by xD** [comment]
> Portscanning, that explains the strange behavior, but not why you portscanned my server...
> 
> I guess i can enable nuvotifier an votingplugin again then

I'm port scanning all IPs, I'm not targeting you specifically
