### ISSUE TITLE
NPE on startup

### ISSUE THREAD

**Issue by hyWse** [parallelblock/NuVotifier#114]
Hey,
when the proxy starts, the following error occurs in the console:

```
21:32:19 [WARNING] Exception encountered when loading plugin: NuVotifier
java.lang.NullPointerException
    at com.vexsoftware.votifier.support.forwarding.cache.FileVoteCache.load(FileVoteCache.java:63)
    at com.vexsoftware.votifier.support.forwarding.cache.FileVoteCache.<init>(FileVoteCache.java:32)
    at com.vexsoftware.votifier.bungee.NuVotifier.loadAndBind(NuVotifier.java:223)
    at com.vexsoftware.votifier.bungee.NuVotifier.onEnable(NuVotifier.java:286)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:226)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:280)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```

I built NuVotifier again with Gradle, but the error remains.
I also deleted the file "cached-votes.json".

**Comment by Ichbinjoe** [comment]
Please post your configuration.

**Comment by hyWse** [comment]
My configuration: https://pastebin.com/M0rPPmsu

Since this error occurs, votes are no longer sent to the sub servers.

**Comment by hyWse** [comment]
2.4.1

**Comment by Ichbinjoe** [comment]
And also to confirm, you deleted cached-votes.json and it did not come back. Correct?

**Comment by hyWse** [comment]
The file is gone and didn't come back until now.
