### ISSUE TITLE
Restarting Server Causes Plugin to Fail?

### ISSUE THREAD

**Issue by Kqliber** [parallelblock/NuVotifier#66]
v2.3.6

I updated the plugin and on initial startup, the plugin was working. Then when I restarted my server voting suddenly isn't working. I looked at the logs and the plugin didn't even startup due to this error:

`[14:05:53] [Server thread/INFO]: [Votifier] Enabling Votifier v2.3.6
[14:05:53] [Server thread/ERROR]: [Votifier] Error reading configuration file or RSA tokens
java.lang.IllegalArgumentException: Illegal base64 character 20
    at java.util.Base64$Decoder.decode0(Base64.java:714) ~[?:1.8.0_161]
    at java.util.Base64$Decoder.decode(Base64.java:526) ~[?:1.8.0_161]
    at java.util.Base64$Decoder.decode(Base64.java:549) ~[?:1.8.0_161]
    at com.vexsoftware.votifier.net.protocol.v1crypto.RSAIO.load(RSAIO.java:74) ~[nuvotifier-universal-2.3.6.jar:?]
    at com.vexsoftware.votifier.NuVotifierBukkit.onEnable(NuVotifierBukkit.java:182) [nuvotifier-universal-2.3.6.jar:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [minecraft_server.jar:git-Spigot-4bd94dc-f4ca180]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [minecraft_server.jar:git-Spigot-4bd94dc-f4ca180]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [minecraft_server.jar:git-Spigot-4bd94dc-f4ca180]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [minecraft_server.jar:git-Spigot-4bd94dc-f4ca180]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [minecraft_server.jar:git-Spigot-4bd94dc-f4ca180]
    at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [minecraft_server.jar:git-Spigot-4bd94dc-f4ca180]
    at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [minecraft_server.jar:git-Spigot-4bd94dc-f4ca180]
    at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [minecraft_server.jar:git-Spigot-4bd94dc-f4ca180]
    at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [minecraft_server.jar:git-Spigot-4bd94dc-f4ca180]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [minecraft_server.jar:git-Spigot-4bd94dc-f4ca180]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[14:05:54] [Server thread/ERROR]: [Votifier] Votifier did not initialize properly!`

I then deleted my whole NuVotifier Folder and the jar itself and replaced it for a new public.key, everything was working fine again, votes were sending through. So I restarted my server again and the same error occurred.

**Comment by Ichbinjoe** [comment]
I have never seen this before, and find it surprising as this code was almost directly pulled from even the original votifier. Please post the public key in your rsa directory, however, after you post the file please delete it, as it exposes your public key (don't go using it on voting websites).

**Comment by Kqliber** [comment]
My public.key:

MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqAX4dXdGfVmglgSuJzxtc5eQ1IUZqiqyYuUaUlOUCAEvSp6k5z8CzoHiW5JesqycwPZ4ypSP2eR03D/+OTlsqIKwlFxN88FCGheMaN/Hw1/JpcmOpjNONYDZc2opn1JO/CZ2I1eEnqNmQZ8aBLMAwo7TfJFuaJVytMKIbXVVfB4QwKE7agJcC8hGAcgxzp9ykJDhf9hRzDQKYu/aL4sSiSIeR09yJFGVx6JHCkNFKcAEiCLsCHvKiOOUVUFg552IY9HnVb9HTdhjr+U72hdOG+g0b0UQjBxYlhpWGLZxgPADraZnmVVA/WSFJ5kiHqhFF36KCUKiSj7B0UW2G8w9XwIDAQAB

**Comment by Ichbinjoe** [comment]
With this key are you still having these issues?

**Comment by Ichbinjoe** [comment]
No response in almost a month.
