### ISSUE TITLE
Bungeecord configuration throws port out of range exception

### ISSUE THREAD

**Issue by fishb6nes** [parallelblock/NuVotifier#79]
Following the Bungeecord setup using plugin messaging as described at: https://github.com/parallelblock/NuVotifier/blob/master/docs/usage.md and setting the port to -1 the plugin still crashes even though the forwarding method has been set to `pluginMessaging`. 

Would you be able to advice?
Many thanks,

Stack trace:
```
[12:48:18 ERROR]: Error occurred while enabling Votifier v2.3.6 (Is it up to date?)
java.lang.IllegalArgumentException: port out of range:-1
        at java.net.InetSocketAddress.checkPort(InetSocketAddress.java:143) ~[?:1.8.0_151]
        at java.net.InetSocketAddress.<init>(InetSocketAddress.java:224) ~[?:1.8.0_151]
        at com.vexsoftware.votifier.netty.util.internal.SocketUtils$10.run(SocketUtils.java:171) ~[?:?]
        at com.vexsoftware.votifier.netty.util.internal.SocketUtils$10.run(SocketUtils.java:168) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_151]
        at com.vexsoftware.votifier.netty.util.internal.SocketUtils.socketAddress(SocketUtils.java:168) ~[?:?]
        at com.vexsoftware.votifier.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:261) ~[?:?]
        at com.vexsoftware.votifier.NuVotifierBukkit.onEnable(NuVotifierBukkit.java:252) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

config.yml:
```
# The IP to listen to. Use 0.0.0.0 if you wish to listen to all interfaces on your server. (All IP addresses)
# This defaults to the IP you have configured your server to listen on, or 0.0.0.0 if you have not configured this.
host: 127.0.0.1

# Port to listen for new votes on
port: -1

# Whether or not to print debug messages. In a production system, this should be set to false.
# This is useful when initially setting up NuVotifier to ensure votes are being delivered.
debug: false

# Setting this option to true will disable handling of Protocol v1 packets. While the old protocol is not secure, this
# option is currently not recommended as most voting sites only support the old protocol at present. However, if you are
# using NuVotifier's proxy forwarding mechanism, enabling this option will increase your server's security.
disable-v1-protocol: false

# All tokens, labeled by the serviceName of each server list.
tokens:
  # Default token for all server lists, if another isn't supplied.
  default: <snip>

# Configuration section for all vote forwarding to NuVotifier
forwarding:
  # Sets whether to set up a remote method for fowarding. Supported methods:
  # - none - Does not set up a forwarding method.
  # - pluginMessaging - Sets up plugin messaging
  method: pluginMessaging
  pluginMessaging:
    channel: NuVotifier
```

**Comment by fishb6nes** [comment]
Whoops, this appears to have been fixed in the CI version!
