### ISSUE TITLE
IllegalStateException: zip file closed

### ISSUE THREAD

**Issue by mibby** [parallelblock/NuVotifier#80]
nuVotifier 2.3.7
Paper dev 1413 (Spigot 1.12.2)

Noticed this error on an automated restart (shut-down process).
```
[09:00:58] [nioEventLoopGroup-2-1/WARN]: [com.vexsoftware.votifier.netty.util.concurrent.AbstractEventExecutor] A task raised an exception. Task: com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext$13@20339ad7
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686) ~[?:1.8.0_172]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:315) ~[?:1.8.0_172]
	at java.util.jar.JarFile.getEntry(JarFile.java:240) ~[?:1.8.0_172]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:223) ~[?:1.8.0_172]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:120) ~[patched_1.12.2.jar:git-Paper-1413]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1413]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_172]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_172]
	at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.notifyOutboundHandlerException(AbstractChannelHandlerContext.java:837) ~[nuvotifier.jar:?]
	at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:626) ~[nuvotifier.jar:?]
	at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.access$1100(AbstractChannelHandlerContext.java:38) ~[nuvotifier.jar:?]
	at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext$13.run(AbstractChannelHandlerContext.java:613) ~[nuvotifier.jar:?]
	at com.vexsoftware.votifier.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [nuvotifier.jar:?]
	at com.vexsoftware.votifier.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [nuvotifier.jar:?]
	at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [nuvotifier.jar:?]
	at com.vexsoftware.votifier.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [nuvotifier.jar:?]
	at com.vexsoftware.votifier.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [nuvotifier.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]

```

**Comment by Ichbinjoe** [comment]
Not sure what can be done, but I'll try to clean this up when I have time. Thanks for reporting.

**Comment by mibby** [comment]
@Ichbinjoe Any update on possibly catching the error during shut-down? 

```
[01:34:13] [nioEventLoopGroup-2-1/WARN]: [com.vexsoftware.votifier.netty.util.concurrent.AbstractEventExecutor] A task raised an exception. Task: com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext$13@7527f9b2
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686) ~[?:1.8.0_172]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:315) ~[?:1.8.0_172]
	at java.util.jar.JarFile.getEntry(JarFile.java:240) ~[?:1.8.0_172]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:223) ~[?:1.8.0_172]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:120) ~[patched_1.12.2.jar:git-Paper-1431]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1431]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_172]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_172]
	at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.notifyOutboundHandlerException(AbstractChannelHandlerContext.java:837) ~[nuvotifier.jar:?]
	at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:626) ~[nuvotifier.jar:?]
	at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.access$1100(AbstractChannelHandlerContext.java:38) ~[nuvotifier.jar:?]
	at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext$13.run(AbstractChannelHandlerContext.java:613) ~[nuvotifier.jar:?]
	at com.vexsoftware.votifier.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [nuvotifier.jar:?]
	at com.vexsoftware.votifier.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [nuvotifier.jar:?]
	at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [nuvotifier.jar:?]
	at com.vexsoftware.votifier.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [nuvotifier.jar:?]
	at com.vexsoftware.votifier.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [nuvotifier.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
```
```
[01:34:15] [nioEventLoopGroup-2-1/WARN]: Exception in thread "nioEventLoopGroup-2-1" java.lang.IllegalStateException: zip file closed
[01:34:15] [nioEventLoopGroup-2-1/WARN]: 	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686)
[01:34:15] [nioEventLoopGroup-2-1/WARN]: 	at java.util.zip.ZipFile.getEntry(ZipFile.java:315)
[01:34:15] [nioEventLoopGroup-2-1/WARN]: 	at java.util.jar.JarFile.getEntry(JarFile.java:240)
[01:34:15] [nioEventLoopGroup-2-1/WARN]: 	at java.util.jar.JarFile.getJarEntry(JarFile.java:223)
[01:34:15] [nioEventLoopGroup-2-1/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:120)
[01:34:15] [nioEventLoopGroup-2-1/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104)
[01:34:15] [nioEventLoopGroup-2-1/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[01:34:15] [nioEventLoopGroup-2-1/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[01:34:15] [nioEventLoopGroup-2-1/WARN]: 	at com.vexsoftware.votifier.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)
[01:34:15] [nioEventLoopGroup-2-1/WARN]: 	at com.vexsoftware.votifier.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)
[01:34:15] [nioEventLoopGroup-2-1/WARN]: 	at com.vexsoftware.votifier.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
[01:34:15] [nioEventLoopGroup-2-1/WARN]: 	at com.vexsoftware.votifier.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
[01:34:15] [nioEventLoopGroup-2-1/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Ichbinjoe** [comment]
This issue is open if someone wants to address it. I do not have the time to address it.
