### ISSUE TITLE
Java error when recieving vote

### ISSUE THREAD

**Issue by fothercat** [parallelblock/NuVotifier#84]
Sponge version: spongeforge-1.12.2-2611-7.1.0-BETA-3002
Error message when recieving a vote:(i blanked out ip's)

[07:44:11] [nioEventLoopGroup-2-1/INFO] [nuvotifier]: Got a protocol v1 vote record from /x.x.x.x:53550 -> Vote (from:ftbservers.com username:fother address:x.x.x.x timeStamp:1526888651)
[07:44:11] [pool-3-thread-3/ERROR] [Sponge]: The Scheduler tried to run the task nuvotifier-A-90 owned by Plugin{id=nuvotifier, name=NuVotifier, version=2.3.4, source=/home/admin/dw20/mods/nuvotifier-universal-2.3.4.jar}, but an error occured.
java.lang.NoClassDefFoundError: org/spongepowered/api/event/cause/NamedCause
        at com.vexsoftware.votifier.sponge.VotifierPlugin$3.run(VotifierPlugin.java:355) ~[VotifierPlugin$3.class:?]
        at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2611-7.1.0-BETA-3002]
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:186) ~[SchedulerBase.class:1.12.2-2611-7.1.0-BETA-3002]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by Ichbinjoe** [comment]
Update NuVotifier - it is now on 2.3.7
