### ISSUE TITLE
StackTrace onEnable

### ISSUE THREAD

**Issue by bobdabiulder** [parallelblock/NuVotifier#88]
Every time votifier is enabled, I get this:
`
[06:36:08] [nioEventLoopGroup-2-1/WARN]: Exception in thread "nioEventLoopGroup-2-1" java.lang.IllegalStateException: zip file closed
[06:36:08] [nioEventLoopGroup-2-1/WARN]: at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686)
[06:36:08] [nioEventLoopGroup-2-1/WARN]: at java.util.zip.ZipFile.getEntry(ZipFile.java:315)
[06:36:08] [nioEventLoopGroup-2-1/WARN]: at java.util.jar.JarFile.getEntry(JarFile.java:240)
[06:36:08] [nioEventLoopGroup-2-1/WARN]: at java.util.jar.JarFile.getJarEntry(JarFile.java:223)
[06:36:08] [nioEventLoopGroup-2-1/WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:120)
[06:36:08] [nioEventLoopGroup-2-1/WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104)
[06:36:08] [nioEventLoopGroup-2-1/WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[06:36:08] [nioEventLoopGroup-2-1/WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[06:36:08] [nioEventLoopGroup-2-1/WARN]: at com.vexsoftware.votifier.netty.buffer.PoolArena.freeChunk(PoolArena.java:293)
[06:36:08] [nioEventLoopGroup-2-1/WARN]: at com.vexsoftware.votifier.netty.buffer.PoolThreadCache$MemoryRegionCache.freeEntry(PoolThreadCache.java:472)
[06:36:08] [nioEventLoopGroup-2-1/WARN]: at com.vexsoftware.votifier.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:442)
[06:36:08] [nioEventLoopGroup-2-1/WARN]: at com.vexsoftware.votifier.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:434)
[06:36:08] [nioEventLoopGroup-2-1/WARN]: at com.vexsoftware.votifier.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:291)
[06:36:08] [nioEventLoopGroup-2-1/WARN]: at com.vexsoftware.votifier.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:282)
[06:36:08] [nioEventLoopGroup-2-1/WARN]: at com.vexsoftware.votifier.netty.buffer.PoolThreadCache.free0(PoolThreadCache.java:255)
[06:36:08] [nioEventLoopGroup-2-1/WARN]: at com.vexsoftware.votifier.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:251)
[06:36:08] [nioEventLoopGroup-2-1/WARN]: at com.vexsoftware.votifier.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.onRemoval(PooledByteBufAllocator.java:449)
[06:36:08] [nioEventLoopGroup-2-1/WARN]: at com.vexsoftware.votifier.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.onRemoval(PooledByteBufAllocator.java:426)
[06:36:08] [nioEventLoopGroup-2-1/WARN]: at com.vexsoftware.votifier.netty.util.concurrent.FastThreadLocal.remove(FastThreadLocal.java:226)
[06:36:08] [nioEventLoopGroup-2-1/WARN]: at com.vexsoftware.votifier.netty.util.concurrent.FastThreadLocal.removeAll(FastThreadLocal.java:67)
[06:36:08] [nioEventLoopGroup-2-1/WARN]: at com.vexsoftware.votifier.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:140)
[06:36:08] [nioEventLoopGroup-2-1/WARN]: at java.lang.Thread.run(Thread.java:748)
`

**Comment by Ichbinjoe** [comment]
Send your entire startup log.

There was a fix pushed recently that fixed this onDisable.

Make sure you are starting the server again, not just plugman enabling it.

**Comment by Ichbinjoe** [comment]
Closing - please reopen if you have any additional information.
