### ISSUE TITLE
Plugin messaging broken on 1.13

### ISSUE THREAD

**Issue by KateHutch** [parallelblock/NuVotifier#90]
I understand that NuVotifier hasn't been updated to 1.13 yet, but I thought I'd just report one thing that needs to be updated (in case it's not already known).

This error occurs loading NuVotifier on Spigot 1.13:
```
[04:43:34] [Server thread/INFO]: [Votifier] Enabling Votifier v2.3.7
[04:43:34] [Server thread/INFO]: [Votifier] Loaded token for website: default
[04:43:34] [Server thread/INFO]: [Votifier] DEBUG mode enabled!
[04:43:34] [Server thread/INFO]: [Votifier] ------------------------------------------------------------------------------
[04:43:34] [Server thread/INFO]: [Votifier] Your Votifier port is less than 0, so we assume you do NOT want to start the
[04:43:34] [Server thread/INFO]: [Votifier] votifier port server! Votifier will not listen for votes over any port, and
[04:43:34] [Server thread/INFO]: [Votifier] will only listen for pluginMessaging forwarded votes!
[04:43:34] [Server thread/INFO]: [Votifier] ------------------------------------------------------------------------------
[04:43:34] [Server thread/ERROR]: [Votifier] NuVotifier could not set up PluginMessaging for vote forwarding!
java.lang.IllegalArgumentException: Channel must contain : separator
    at org.bukkit.plugin.messaging.StandardMessenger.validateAndCorrectChannel(StandardMessenger.java:474) ~[spigot-1.13-R0.1-SNAPSHOT.jar:git-Spigot-5eb3921-5870145]
    at org.bukkit.plugin.messaging.StandardMessenger.registerIncomingPluginChannel(StandardMessenger.java:209) ~[spigot-1.13-R0.1-SNAPSHOT.jar:git-Spigot-5eb3921-5870145]
    at com.vexsoftware.votifier.forwarding.BukkitPluginMessagingForwardingSink.<init>(BukkitPluginMessagingForwardingSink.java:24) ~[nuvotifier.jar:?]
    at com.vexsoftware.votifier.NuVotifierBukkit.onEnable(NuVotifierBukkit.java:284) [nuvotifier.jar:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [spigot-1.13-R0.1-SNAPSHOT.jar:git-Spigot-5eb3921-5870145]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13-R0.1-SNAPSHOT.jar:git-Spigot-5eb3921-5870145]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13-R0.1-SNAPSHOT.jar:git-Spigot-5eb3921-5870145]
    at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:424) [spigot-1.13-R0.1-SNAPSHOT.jar:git-Spigot-5eb3921-5870145]
    at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:338) [spigot-1.13-R0.1-SNAPSHOT.jar:git-Spigot-5eb3921-5870145]
    at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:562) [spigot-1.13-R0.1-SNAPSHOT.jar:git-Spigot-5eb3921-5870145]
    at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:524) [spigot-1.13-R0.1-SNAPSHOT.jar:git-Spigot-5eb3921-5870145]
    at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:423) [spigot-1.13-R0.1-SNAPSHOT.jar:git-Spigot-5eb3921-5870145]
    at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:288) [spigot-1.13-R0.1-SNAPSHOT.jar:git-Spigot-5eb3921-5870145]
    at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686) [spigot-1.13-R0.1-SNAPSHOT.jar:git-Spigot-5eb3921-5870145]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

Messaging channels need to be set as "plugin name:channel name" in 1.13.

**Comment by Ichbinjoe** [comment]
yay. much excite......

gotta love api changes that really don't have to be made but hey, what can I say.

**Comment by Ichbinjoe** [comment]
i'm going to change the default configuration value to have NuVotifier:NuVotifier instead of appending it in code... just in case someone really wants it named differently. Most people don't change the config anyways so it shouldn't be a big deal.

**Comment by danjono** [comment]
The plugin channel name also needs to be lowercase as well as have a colon.
