### ISSUE TITLE
Error on first start (Sponge)

### ISSUE THREAD

**Issue by sapphirepixelmon** [parallelblock/NuVotifier#92]
Hi :)

Just downloaded the jar and put it on my server. When trying to start the server for the first time with the plugin I get the following error:

```
20.08 19:56:06 [Server] Server thread/ERROR [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
20.08 19:56:06 [Server] INFO net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from NuVotifier (nuvotifier)
20.08 19:56:06 [Server] INFO Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:
20.08 19:56:06 [Server] INFO 1) Could not find a suitable constructor in com.vexsoftware.votifier.sponge.VotifierPlugin. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
20.08 19:56:06 [Server] INFO at com.vexsoftware.votifier.sponge.VotifierPlugin.class(VotifierPlugin.java:56)
20.08 19:56:06 [Server] INFO at org.spongepowered.common.inject.plugin.PluginModule.configure(PluginModule.java:59)
20.08 19:56:06 [Server] INFO 1 error
20.08 19:56:06 [Server] INFO at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3361.jar:1.12.2-2705-7.1.0-BETA-3361]
20.08 19:56:06 [Server] INFO at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3361.jar:1.12.2-2705-7.1.0-BETA-3361]
20.08 19:56:06 [Server] INFO at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3361.jar:1.12.2-2705-7.1.0-BETA-3361]
20.08 19:56:06 [Server] INFO at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:232) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3361.jar:1.12.2-2705-7.1.0-BETA-3361]
20.08 19:56:06 [Server] INFO at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:236) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3361.jar:1.12.2-2705-7.1.0-BETA-3361]
20.08 19:56:06 [Server] INFO at org.spongepowered.mod.plugin.SpongeModPluginContainer.constructMod(SpongeModPluginContainer.java:282) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3361.jar:1.12.2-2705-7.1.0-BETA-3361]
20.08 19:56:06 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
20.08 19:56:06 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
20.08 19:56:06 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
20.08 19:56:06 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
20.08 19:56:06 [Server] INFO at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
20.08 19:56:06 [Server] INFO at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
20.08 19:56:06 [Server] INFO at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
20.08 19:56:06 [Server] INFO at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
20.08 19:56:06 [Server] INFO at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
20.08 19:56:06 [Server] INFO at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
20.08 19:56:06 [Server] INFO at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
20.08 19:56:06 [Server] INFO at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218) ~[forge-1.12.2-14.23.4.2705-universal.jar:?]
20.08 19:56:06 [Server] INFO at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196) ~[forge-1.12.2-14.23.4.2705-universal.jar:?]
20.08 19:56:06 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
20.08 19:56:09 [Multicraft] Server shut down (starting)
20.08 19:56:09 [Multicraft] Not restarting crashed server.
20.08 19:56:09 [Multicraft] Server stopped
```

Greetings,

**Comment by Ichbinjoe** [comment]
Grab latest from here https://repo.parallelblock.com/repository/public-raw/nuvotifier/nuvotifier.jar

reopen if this doesn't fix it
